### ISSUE TITLE
Error: Unable to exec

### ISSUE THREAD

**Issue by Otsel** [karikera/ftp-kr#103]
Getting this upon connection. 

```
Connected
Error: Unable to exec
	at /Users/aaronwickman/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/ssh2/lib/client.js:1374:19
	at SSH2Stream.<anonymous> (/Users/aaronwickman/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/ssh2/lib/Channel.js:205:24)
	at emitNone (events.js:86:13)
	at SSH2Stream.emit (events.js:188:7)
	at parsePacket (/Users/aaronwickman/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/ssh2-streams/lib/ssh.js:3508:10)
	at SSH2Stream._transform (/Users/aaronwickman/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/ssh2-streams/lib/ssh.js:669:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (/Users/aaronwickman/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/ssh2-streams/lib/ssh.js:251:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at SSH2Stream.Writable.write (_stream_writable.js:241:11)
	at Socket.ondata (_stream_readable.js:557:20)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at TCP.onread (net.js:560:20)
	at Object.promiseErrorWrap (/Users/aaronwickman/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/src/util/util.ts:247:15)
	at SftpConnection.exec (/Users/aaronwickman/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/src/vsutil/sftp.ts:99:9)
	at SftpConnection.pwd (/Users/aaronwickman/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/src/vsutil/sftp.ts:122:14)
	at FtpManager.<anonymous> (/Users/aaronwickman/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/src/ftpmgr.ts:318:32)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/aaronwickman/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpmgr.js:4:58)
	at <anonymous>
```

Thoughts?

**Comment by kokolita** [comment]
Hey @Otsel did you ever figure this out? Getting the same error with my STFP connection.

**Comment by Otsel** [comment]
> Hey @Otsel did you ever figure this out? Getting the same error with my STFP connection.

Hey @kokolita, truth be told that during debugging I came to realize this project isn't receiving support and made the switch to [this extension](https://github.com/humy2833/FTP-Simple) instead.

Works great and haven't had any issues since!
