### ISSUE TITLE
There an error when uppload image file. Can you fixed it?

### ISSUE THREAD

**Issue by touxing** [karikera/ftp-kr#107]
I upload an image directory that does not exist, then error here. I hope you can solve it. Thinks.

Task: Upload All
platform: win32
arch: x64

[Error]
message: /beautify4th/image: Ã¦Â²Â¡Ã¦ÂÂÃ©ÂÂ£Ã¤Â¸ÂªÃ¦ÂÂÃ¤Â»Â¶Ã¦ÂÂÃ§ÂÂ®Ã¥Â½Â[450]
code: 450

[Stack Trace]
Error: /beautify4th/image: Ã¦Â²Â¡Ã¦ÂÂÃ©ÂÂ£Ã¤Â¸ÂªÃ¦ÂÂÃ¤Â»Â¶Ã¦ÂÂÃ§ÂÂ®Ã¥Â½Â
	at makeError ([ftp-kr]\node_modules\ftp\lib\connection.js:1067:13)
	at Parser.<anonymous> ([ftp-kr]\node_modules\ftp\lib\connection.js:113:25)
	at emitTwo (events.js:126:13)
	at Parser.emit (events.js:214:7)
	at Parser._write ([ftp-kr]\node_modules\ftp\lib\parser.js:59:10)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at Parser.Writable.write (_stream_writable.js:290:11)
	at Socket.ondata ([ftp-kr]\node_modules\ftp\lib\connection.js:273:20)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:246:13)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at TCP.onread (net.js:594:20)
	at Object.promiseErrorWrap ([ftp-kr]\out\src\util\util.ts:247:15)
	at FtpConnection.list ([ftp-kr]\out\src\vsutil\fileinterface.ts:164:9)
	at _blockTestWrap.client ([ftp-kr]\out\src\ftpmgr.ts:356:50)
	at FtpManager.<anonymous> ([ftp-kr]\out\src\ftpmgr.ts:142:47)
	at Generator.next (<anonymous>)
	at C:\Users\Administrator\.vscode-insiders\extensions\ruakr.ftp-kr-1.3.16\out\ftpmgr.js:7:71
	at new Promise (<anonymous>)
	at __awaiter ([ftp-kr]\out\ftpmgr.js:3:12)
	at util_1.promiseErrorWrap.connect.then ([ftp-kr]\out\src\ftpmgr.ts:136:65)
	at <anonymous>
	at Object.promiseErrorWrap ([ftp-kr]\out\src\util\util.ts:247:15)
	at FtpManager._blockTestWrap ([ftp-kr]\out\src\ftpmgr.ts:136:9)
	at FtpManager.list ([ftp-kr]\out\src\ftpmgr.ts:356:14)
	at FtpCacher.<anonymous> ([ftp-kr]\out\src\ftpcacher.ts:583:40)
	at Generator.next (<anonymous>)
	at fulfilled ([ftp-kr]\out\ftpcacher.js:4:58)
	at <anonymous>

[ftp-kr.json]
{
    "host": "xxx.xx.xx.xxx",
    "username": "I tell you",
    "password": "********",
    "remotePath": "/",
    "localBasePath": "./",
    "protocol": "ftp",
    "port": 0,
    "fileNameEncoding": "utf8",
    "autoUpload": false,
    "autoDelete": false,
    "autoDownload": false,
    "ignore": [
        ".git",
        "/.vscode"
    ]
}

**Comment by touxing** [comment]
I'm so sorry to disturb you. Wait a moment, I upload the image directory successfully. Maybe network error?
