### ISSUE TITLE
ftp-kr Error

### ISSUE THREAD

**Issue by yaochengfly** [karikera/ftp-kr#110]
ENOENT: no such file or directory, stat 'extension-output-#5'
	at File.stat (/Users/tanyaocheng/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/krfile/out/index.js:271:16)
	at File.isDirectory (/Users/tanyaocheng/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/krfile/out/index.js:340:21)
	at Object.<anonymous> (/Users/tanyaocheng/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/src/cmd/ftpsync.ts:143:44)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/tanyaocheng/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/cmd/ftpsync.js:4:58)
	at <anonymous>
ENOENT: no such file or directory, stat 'extension-output-#5'
	at File.stat (/Users/tanyaocheng/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/krfile/out/index.js:271:16)
	at File.isDirectory (/Users/tanyaocheng/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/krfile/out/index.js:340:21)
	at Object.<anonymous> (/Users/tanyaocheng/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/src/cmd/ftpsync.ts:143:44)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/tanyaocheng/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/cmd/ftpsync.js:4:58)
	at <anonymous>

**Comment by yaochengfly** [comment]
So sorry about this. it's my fault. 
my keybinding conflicted. this is another plug-in error. and i uninstall it!!!
