### ISSUE TITLE
[short-cut error]upload this command

### ISSUE THREAD

**Issue by khzero** [karikera/ftp-kr#12]
I usally use command "upload this" by \<shift\>+\<p\> and type upload this
I want to use easy to this then I put it on shortcut command
but the error comes.... another command in your extension on shortcut doesn't matter
how should I do?

[TypeError]
message: Path must be a string. Received undefined
[Stack Trace]
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at Object.worklize (C:\Users\young\.vscode\extensions\ruakr.ftp-kr-1.0.6\out\fs.js:37:27)
    at fileOrEditorFile (C:\Users\young\.vscode\extensions\ruakr.ftp-kr-1.0.6\out\ex\ftpsync.js:189:29)
    at cfg.loadTest.then.then (C:\Users\young\.vscode\extensions\ruakr.ftp-kr-1.0.6\out\ex\ftpsync.js:224:29)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by karikera** [comment]
Thanks for reporting
i will fix it in 1.0.9 update.
I could not expect that shortcut action has empty object parameter.
