### ISSUE TITLE
message: Non-anonymous sessions must use encryption.[530]

### ISSUE THREAD

**Issue by chiragpurohit71085** [karikera/ftp-kr#135]
I am suddenly started getting this error.  I checked in filezilla and it has started using 

````

<Host>xx.xx.xxx.xx</Host>
				<Port>21</Port>
				<Protocol>0</Protocol>
				<Type>0</Type>
				<User>xxxxxxxx</User>
				<Pass encoding="base64">xxxxxxxxx=</Pass>

````

Here is the error log
````
ask: First Connect
platform: darwin
arch: x64

[Error]
message: Non-anonymous sessions must use encryption.[530]
code: 530

[Stack Trace]
Error: Non-anonymous sessions must use encryption.
	at makeError ([ftp-kr]/node_modules/ftp/lib/connection.js:1067:13)
	at Parser.<anonymous> ([ftp-kr]/node_modules/ftp/lib/connection.js:113:25)
	at Parser.emit (events.js:200:13)
	at Parser._write ([ftp-kr]/node_modules/ftp/lib/parser.js:59:10)
	at doWrite (_stream_writable.js:417:12)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Parser.Writable.write (_stream_writable.js:301:11)
	at Socket.ondata ([ftp-kr]/node_modules/ftp/lib/connection.js:273:20)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
	at Object.promiseErrorWrap ([ftp-kr]/out/src/util/util.ts:247:15)
	at FtpConnection.connect ([ftp-kr]/out/src/vsutil/fileinterface.ts:39:9)
	at /Users/greesha/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpmgr.js:180:68
	at Generator.next (<anonymous>)
	at /Users/greesha/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpmgr.js:7:71
	at new Promise (<anonymous>)
	at __awaiter ([ftp-kr]/out/ftpmgr.js:3:12)
	at tryToConnect ([ftp-kr]/out/ftpmgr.js:175:24)
	at FtpManager.<anonymous> ([ftp-kr]/out/src/ftpmgr.ts:298:10)
	at Generator.next (<anonymous>)
	at /Users/greesha/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpmgr.js:7:71
	at new Promise (<anonymous>)
	at __awaiter ([ftp-kr]/out/ftpmgr.js:3:12)
	at FtpManager.connect ([ftp-kr]/out/ftpmgr.js:160:16)
	at FtpCacher.<anonymous> ([ftp-kr]/out/src/ftpcacher.ts:579:22)
	at Generator.next (<anonymous>)
	at /Users/greesha/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpcacher.js:7:71
	at new Promise (<anonymous>)
	at __awaiter ([ftp-kr]/out/ftpcacher.js:3:12)
	at /Users/greesha/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpcacher.js:443:27
	at /Users/greesha/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpcacher.js:459:16
	at Scheduler.task ([ftp-kr]/out/src/vsutil/work.ts:302:10)
	at FtpCacher.ftpList ([ftp-kr]/out/src/ftpcacher.ts:565:24)
	at FtpCacher.<anonymous> ([ftp-kr]/out/src/ftpcacher.ts:147:14)
	at Generator.next (<anonymous>)
	at /Users/greesha/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpcacher.js:7:71
	at new Promise (<anonymous>)
	at __awaiter ([ftp-kr]/out/ftpcacher.js:3:12)
	at TaskImpl.task ([ftp-kr]/out/src/ftpcacher.ts:146:60)
	at TaskImpl.<anonymous> ([ftp-kr]/out/src/vsutil/work.ts:98:20)
	at Generator.next (<anonymous>)
	at /Users/greesha/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/vsutil/work.js:7:71
	at new Promise (<anonymous>)
	at __awaiter ([ftp-kr]/out/vsutil/work.js:3:12)
	at TaskImpl.play ([ftp-kr]/out/vsutil/work.js:67:16)
	at Scheduler.progress ([ftp-kr]/out/src/vsutil/work.ts:337:20)
	at Scheduler.task ([ftp-kr]/out/src/vsutil/work.ts:312:8)
	at FtpCacher.init ([ftp-kr]/out/src/ftpcacher.ts:146:24)
	at /Users/greesha/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/watcher.js:76:40
	at /Users/greesha/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/util/event.js:52:46
	at Generator.next (<anonymous>)
	at fulfilled ([ftp-kr]/out/util/event.js:4:58)

[ftp-kr.json]
{
    "host": "xx.xx.xxx.xx",
    "username": "xxxxxx",
    "password": "xxx",
    "remotePath": "/",
    "protocol": "ftp",
    "port": 0,
    "fileNameEncoding": "utf8",
    "autoUpload": false,
    "autoDelete": false,
    "autoDownload": false,
    "refreshTime": 10000000,
    "createSyncCache": false,
    "connectionTimeout": 6000000,
    "ignore": [
        ".git",
        "/.vscode"
    ]
}

````

**Comment by chiragpurohit71085** [comment]
If any body faces this issue,

add 

"secure":true, 

in ftp-kr.json
