### ISSUE TITLE
Permission denied when uploading file, but winscp works fine

### ISSUE THREAD

**Issue by jack-liew** [karikera/ftp-kr#153]
Hi:
I have a tp-link "wdr8660" router with a usb port, the router provides ftp service to access the usb hard disk. and ftp must be set to passive mode.

I can use winscp to add and delete files on ftp,  but, it cannot be write to ftp server to use ftp-kr or other ftp plug of vscode,  but only download files.

what should i do?

Thanks

Error message:
/a/b.png: Permission denied.[550]
Error: ftp-kr Task failed, more information in the output
    at Logger.errorConfirm (d:\VSCode\data\extensions\ruakr.ftp-kr-1.3.22\src\vsutil\log.ts:215:12)
    at confirmer (d:\VSCode\data\extensions\ruakr.ftp-kr-1.3.22\src\ftpcacher.ts:765:34)
    at FtpCacher.<**_anonymous_**> (d:\VSCode\data\extensions\ruakr.ftp-kr-1.3.22\src\ftpcacher.ts:732:24)
    at Generator.next (<anonymous>)
    at fulfilled (d:\VSCode\data\extensions\ruakr.ftp-kr-1.3.22\out\index.bundle.js:3532:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by karikera** [comment]
Sorry about the late reply.
it seems it's a pretty backend issue.
Could you provide the settings of WinSCP?
I cannot assume the difference.

**Comment by karikera** [comment]
I guess it's fixed now.

**Comment by jack-liew** [comment]
> Sorry about the late reply. it seems it's a pretty backend issue. Could you provide the settings of WinSCP? I cannot assume the difference.

----
Hi:
  When I use winscp with ftp protocol, the upload function is available.
![image](https://user-images.githubusercontent.com/102201538/208685998-240f4e6c-b12c-40e4-ac33-b3e0434debc0.png)

But in vscode with ftp-kr, Error prompt:upload fail: /volume9/notes/2110291615-1.pdf, Permission denied.
![image](https://user-images.githubusercontent.com/102201538/208688435-f0f09337-2c3a-4c95-ac00-8b3ab963d24b.png)

Thank U~~~

**Comment by karikera** [comment]
the plugin is updated to 1.4.4 recently. I hope it's fixed.

**Comment by jack-liew** [comment]
> the plugin is updated to 1.4.4 recently. I hope it's fixed.

Error  In Vscode:

upload /volume9/notes/aaa
upload fail: /volume9/notes/aaa, Permission denied.
Error: Permission denied.
    at makeError (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/node_modules/ftp/lib/connection.js:1067:13)
    **at Parser.<anonymous> (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/node_modules/ftp/lib/connection.js:113:25)**
    at Parser.emit (node:events:526:28)
    at Parser._write (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/node_modules/ftp/lib/parser.js:59:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Parser.Writable.write (node:internal/streams/writable:334:10)
    at Socket.ondata (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/node_modules/ftp/lib/connection.js:273:20)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at promiseErrorWrap (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/util/util.ts:211:16)
    at FtpConnection.upload (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/vsutil/fileinterface.ts:106:26)
    at /home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/ftpmgr.ts:376:11
    at /home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/ftpmgr.ts:175:49
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at next (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/ftpcacher.ts:497:8)
    at TaskImpl.task (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/ftpcacher.ts:521:26)
    at promiseErrorWrap (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/util/util.ts:211:16)
    at FtpManager._blockTestWrap (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/ftpmgr.ts:168:26)
    at FtpManager.upload (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/ftpmgr.ts:375:15)
    at /home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/ftpcacher.ts:436:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at next (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/ftpcacher.ts:497:8)
    at TaskImpl.task (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/src/ftpcacher.ts:521:26)

---
I am not using anonymous users

 **at Parser.<anonymous> (/home/jack/.vscode/extensions/ruakr.ftp-kr-1.4.4/node_modules/ftp/lib/connection.js:113:25)**

---
Thank U and great work
