### ISSUE TITLE
Connected Error: Unable to exec

### ISSUE THREAD

**Issue by bnovak99** [karikera/ftp-kr#157]
I'm able to connect but with errors. Cannot download or upload to WPengine. No problem with other hosts.

Error: Unable to exec
    at /Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/ssh2/lib/client.js:1728:39
    at CHANNEL_FAILURE (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/ssh2/lib/client.js:599:39)
    at 100 (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/ssh2/lib/protocol/handlers.misc.js:1212:16)
    at Protocol.onPayload (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/out/index.bundle.js:24902:12)
    at GenericDecipherNative.decrypt (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/ssh2/lib/protocol/crypto.js:1269:26)
    at Protocol.parsePacket [as _parse] (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/ssh2/lib/protocol/Protocol.js:1948:14)
    at Protocol.parse (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/ssh2/lib/protocol/Protocol.js:252:16)
    at Socket.<anonymous> (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/ssh2/lib/client.js:713:21)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at promiseErrorWrap (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/src/util/util.ts:251:16)
    at SftpConnection.exec (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/src/vsutil/sftp.ts:97:26)
    at SftpConnection.pwd (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/src/vsutil/sftp.ts:120:15)
    at FtpManager.<anonymous> (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/src/ftpmgr.ts:310:33)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/EMedia/.vscode/extensions/ruakr.ftp-kr-1.3.22/out/index.bundle.js:40623:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by karikera** [comment]
Does WPEngine support SFTP?

**Comment by karikera** [comment]
There doesn't seem to be any activity so I'll close it for now.
