### ISSUE TITLE
File is not in workspace

### ISSUE THREAD

**Issue by sungyongs** [karikera/ftp-kr#35]
Hi,

When I `ftp-kr: init` and set the access settings, I found following error message when I try `ftp-kr: Download all`.
Originally, there are no files or folders in local, and I want to download all files and folders in a remote server by using `ftp-kr: Download all` command. 
In the following example, `README.md` exists on the remote server and doesn't exist in my local machine.

[Error]
message: //path/to/README.md is not in workspace
[Stack Trace]
Error: //path/to/README.md is not in workspace
	at ConfigClass.workpath (/path/to/.vscode/extensions/ruakr.ftp-kr-1.2.5/out/config.js:428:23)
	at FtpCacher.ftppath (/path/to/.vscode/extensions/ruakr.ftp-kr-1.2.5/out/ftpsync.js:73:93)
	at flushList (/path/to/.vscode/extensions/ruakr.ftp-kr-1.2.5/out/ftpsync.js:512:35)
	at FtpCacher.<anonymous> (/path/to/.vscode/extensions/ruakr.ftp-kr-1.2.5/out/ftpsync.js:521:21)
	at Generator.next (<anonymous>)
	at fulfilled (/path/to/.vscode/extensions/ruakr.ftp-kr-1.2.5/out/ftpsync.js:4:58)
	at <anonymous>

**Comment by karikera** [comment]
Does path starts with two slashes?
I changed to custom path functions for some windows path,.. 
Can i ask about path style?..

**Comment by sungyongs** [comment]
`"remotePath": "/home/sungyong/workspace/interpretable-gcn/",`
I think that I can upload files to the remote server correctly, but when I try to download files I got this notification.
`Error: //Users/sungyong/path/to/README.md is not in workspace`

Thanks!

**Comment by karikera** [comment]
does local path need to start with two slashes?
or ..   wrong path?..
