### ISSUE TITLE
안녕하세요 에러 이슈입니다.

### ISSUE THREAD

**Issue by keen0927** [karikera/ftp-kr#54]
업데이트 후에 ftp-kr 첫 오픈때

Error: (SSH) Channel open failure: open failed

이게 뜨네요 다시 세이브 하면 정상 동작 하는데 

서버와 연결해제가 되면 주기적으로 에러 메세지가 나옵니다 ㅠ ㅠ

수고하세요~

**Comment by karikera** [comment]
오류 제보 감사드립니다!
의심되는 곳을 수정해서 업데이트 해봤어요 (1.3.6)
오류가 떴을 때, Detail로 오류나는 위치를 확인해서 보여주시면, 고치는데 도움이 될 것 같아요!

**Comment by keen0927** [comment]
에러 경고문은 계속 나오네요 ㅠㅠ 계속나온다는게 디스컨넥된후 새로 접속할때 무조건 노출 되요ㅠ
에러로그 보내드립니다 
`Task: upload /application/views/layout/master.php
[Error]
message: (SSH) Channel open failure: open failed
[Stack Trace]
Error: (SSH) Channel open failure: open failed
	at SSH2Stream.onFailure (/Users/?/.vscode/extensions/ruakr.ftp-kr-1.3.6/node_modules/ssh2/lib/client.js:1195:13)
	at Object.onceWrapper (events.js:293:19)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (/Users/?/.vscode/extensions/ruakr.ftp-kr-1.3.6/node_modules/ssh2-streams/lib/ssh.js:3708:10)
	at SSH2Stream._transform (/Users/?/.vscode/extensions/ruakr.ftp-kr-1.3.6/node_modules/ssh2-streams/lib/ssh.js:669:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)
	at SSH2Stream._read (/Users/?/.vscode/extensions/ruakr.ftp-kr-1.3.6/node_modules/ssh2-streams/lib/ssh.js:251:15)
	at SSH2Stream.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)`

수고하세요 (_ _)

**Comment by keen0927** [comment]
추가로 제 셋팅 보내드립니다

`
{
    "host": "",
    "username": "",
    "password": "",
    "remotePath": "",
    "protocol": "sftp",
    "port": 22,
    "fileNameEncoding": "utf8",
    "ignoreWrongFileEncoding": false,
    "autoUpload": true,
    "autoDelete": true,
    "autoDownload": true,
    "ignore": [
        ".git",
        "/.vscode/chrome",
        "/.vscode/.key",
        "/.vscode/ftp-kr.task.json",
        "/.vscode/ftp-kr.error.log",
        "/.vscode/ftp-kr.sync.*.json"
    ],
    "sftpOverride": {
        "algorithms": {
            "kex": [
                "diffie-hellman-group1-sha1"
            ],
            "cipher": [
                "3des-cbc"
            ]
        }
    },
    "ignoreJsonUploadCaution": true
}
`

**Comment by karikera** [comment]
문제있는 부분을  찾아, 수정해서 업데이트 하였습니다! (1.3.7)
