### ISSUE TITLE
FTP Stops Working

### ISSUE THREAD

**Issue by joaomaridalho** [karikera/ftp-kr#56]
`[renderer1] [error] Cannot read property 'toString' of undefined: TypeError: Cannot read property 'toString' of undefined
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:544:771
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:729)
    at FtpTree.refresh (C:\Users\username\.vscode\extensions\ruakr.ftp-kr-1.3.7\src\ftptree.ts:39:22)
    at FtpSyncManager.<anonymous> (C:\Users\username\.vscode\extensions\ruakr.ftp-kr-1.3.7\src\ftpsync.ts:92:11)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Nuno\.vscode\extensions\ruakr.ftp-kr-1.3.7\out\ftpsync.js:4:58)
    at <anonymous>`
Hey @karikera,
After this it seems that upload on save stops working.

**Comment by karikera** [comment]
Thanks for reporting!

I fixed it in new update (1.3.8)
It looks like i put wrong parameter to extension api
