### ISSUE TITLE
작동이 안됩니다..ㅠ

### ISSUE THREAD

**Issue by keen0927** [karikera/ftp-kr#63]
업데이트 후에
Trying to connect to sftp://호스트주소// with user 유저네임
Connected
[config loading]task is cancelled

작동이 안되네요..ㅠ 

저번 버전까지 경고문 떠도 기능은 동작했는데 에러로그도 안떠서 요번엔 무슨문제인지 도움을 드릴수가 없네요 ㅠ

**Comment by karikera** [comment]
오류 제보 감사드립니다!
초기화에 오류가 있어서 수정했어요.. (1.3.12 update)

**Comment by keen0927** [comment]
감사합니다 작동은 다시 잘됩니다~

에러로그만 안나오게 어떻게 안될까요 제접할때 계속 떠서;

`Task: config loading
[Error]
message: (SSH) Channel open failure: open failed
[Stack Trace]
Error: (SSH) Channel open failure: open failed

	at Object.errorWrap (/Users/keen/.vscode/extensions/ruakr.ftp-kr-1.3.12/out/util/util.js:206:24)
	at client.exec (/Users/keen/.vscode/extensions/ruakr.ftp-kr-1.3.12/out/vsutil/sftp.js:104:42)
	at /Users/keen/.vscode/extensions/ruakr.ftp-kr-1.3.12/node_modules/ssh2/lib/client.js:726:14
	at SSH2Stream.onFailure (/Users/keen/.vscode/extensions/ruakr.ftp-kr-1.3.12/node_modules/ssh2/lib/client.js:1203:5)
	at Object.onceWrapper (events.js:293:19)
	at emitOne (events.js:96:13)
	at SSH2Stream.emit (events.js:191:7)
	at parsePacket (/Users/keen/.vscode/extensions/ruakr.ftp-kr-1.3.12/node_modules/ssh2-streams/lib/ssh.js:3708:10)
	at SSH2Stream._transform (/Users/keen/.vscode/extensions/ruakr.ftp-kr-1.3.12/node_modules/ssh2-streams/lib/ssh.js:669:13)
	at SSH2Stream.Transform._read (_stream_transform.js:167:10)`

**Comment by karikera** [comment]
버그를 수정하였습니다! (1.3.13)
