### ISSUE TITLE
altServer upload/download/diff error 1.3.12 verison

### ISSUE THREAD

**Issue by kkraszy** [karikera/ftp-kr#64]
Task: Diff
[Error]
message: ENOENT: no such file or directory, open '/my-path/my-project/.vscode/undefined'[ENOENT]
code: ENOENT
errno: -2
[Stack Trace]
Error: ENOENT: no such file or directory, open '/my-path/my-project/.vscode/undefined'[ENOENT]
	at Object.errorWrap (/my-path/.vscode/extensions/ruakr.ftp-kr-1.3.12/out/util/util.js:206:24)
	at _connect.catch.err (/my-path/.vscode/extensions/ruakr.ftp-kr-1.3.12/out/vsutil/fileinterface.js:20:68)
	at <anonymous>

Main Server works great.

**Comment by karikera** [comment]
Thanks for reporting!
I fixed that bug in new update! (1.3.14)

**Comment by kkraszy** [comment]
Thanks, works like a charm.
