### ISSUE TITLE
FTP Explorer isnt working

### ISSUE THREAD

**Issue by Flokki** [karikera/ftp-kr#68]
I'd love to use the FTP Explorer but it doesn't seem to work for me.
Upload and download with normal workingspace works fine.

But whenever I try to open a document directly from the server I get this error message:
Alert:
Server not found: ftp://www.xxxxxxxxxxx.com:21@xxxxxx///index.html
```
Error: Server not found: ftp://www.xxxxxx.com:21@xxxxxx///index.html
	at FtpTree.getServerFromUri (C:\Users\XXXXXl\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:110:15)
	at FtpContentProvider.<anonymous> (C:\Users\XXXXXl\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:38:48)
	at Generator.next (<anonymous>)
	at C:\Users\XXXXXll\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\XXXXXl\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:3:12)
	at FtpContentProvider.provideTextDocumentContent (C:\Users\XXXXXl\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:35:16)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:545:285
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:622
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:75:657)
```

Please help me fix this.
FTP Username and Password are correct. Upload and download works fine with workspace.

**Comment by karikera** [comment]
Thanks for bug reporting!
It looks like ftp-kr has problem to match host url with requested uri..  but I'm not sure where is wrong..
I will try to fix it in next update,

**Comment by danilort** [comment]
FTP-KR is very good exstension.
I have the same problem on EXPLORER (version 1.3.16).
When I clic on the file:
```
Error: Server not found: ftp://ftp.xxxxxxxx.altervista.org:21@xxxxxxxx////phpinfo/prova2.php
        at FtpTree.getServerFromUri (C:\Users\Danilo\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:110:15)
        at FtpContentProvider.<anonymous> (C:\Users\Danilo\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:38:48)
        at Generator.next (<anonymous>)
        at C:\Users\Danilo\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:7:71
        at Promise (<anonymous>)
        at __awaiter (C:\Users\Danilo\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:3:12)
        at FtpContentProvider.provideTextDocumentContent (C:\Users\Danilo\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:35:16)
        at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:548:469
        at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:790
        at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:35)

```

When I clic "Download this":

```
platform: win32
arch: ia32

[Error]
message: /phpinfo/prova2.php is not in remotePath

[Stack Trace]
Error: /phpinfo/prova2.php is not in remotePath
        at FtpCacher.toWorkPathFromFtpPath ([ftp-kr]\out\src\ftpcacher.ts:163:54)
        at FtpCacher.fromFtpPath ([ftp-kr]\out\src\ftpcacher.ts:197:45)
        at FtpCacher.fromFtpFile ([ftp-kr]\out\src\ftpcacher.ts:192:14)
        at C:\Users\Danilo\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\cmd\ftpsync.js:50:31
        at Generator.next (<anonymous>)
        at C:\Users\Danilo\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\cmd\ftpsync.js:7:71
        at Promise (<anonymous>)
        at __awaiter ([ftp-kr]\out\cmd\ftpsync.js:3:12)
        at getInfoToTransfer ([ftp-kr]\out\cmd\ftpsync.js:32:12)
        at Object.<anonymous> ([ftp-kr]\out\src\cmd\ftpsync.ts:164:43)
```

**Comment by lrozewicz** [comment]
I have the same problem with FTP Explorer like Flokki too. Quick-fix I found is change in file: c:\Users\\(UserName)\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js lines: 104 & 108

from

`if (uri.scheme + '://' + uri.authority === server.config.hostUrl) {
                if (uri.path === server.ftp.remotePath || uri.path.startsWith(server.ftp.remotePath + '/')) {
                    return server;
                }
 }`

to

`
//if (uri.scheme + '://' + uri.authority === server.config.hostUrl) {
                if (uri.path === server.ftp.remotePath || uri.path.startsWith(server.ftp.remotePath + '/')) {
                    return server;
                }
//}
`

Now I can open the files but I can't change nothing (opened files from server in editor are readonly...)

 I'd be grateful if you could help me :)

**Comment by marc31** [comment]
Thanks for this plugin.

>I can open the files but I can't change nothing (opened files from server in editor are readonly...) 

I have the same problem file are in readonly mode

**Comment by aderchox** [comment]
Same problem here.

**Comment by maxmax91** [comment]
Same problem. It's a realy pity in 2 years this hasn't been solved, does anybody know what cause it? I thinks it's a server configuration.

**Comment by danilort** [comment]
I no longer use the EXPLORER function
