### ISSUE TITLE
Problem with any server of plesk

### ISSUE THREAD

**Issue by pedami** [karikera/ftp-kr#69]
Error: ftp-kr is busy: [First Connect] is being proceesed. Cannot run [First Connect]
    at Timeout.timeout.setTimeout [as _onTimeout] (/****/*******/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/vsutil/work.ts:78:27)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

Any Idea??

**Comment by karikera** [comment]
It looks like cannot connect to ftp server,

If you try other command when it's connecting, It will show that error,
It try to connect when config loaded, If cannot connect it will retry it,

**Comment by lionhurt** [comment]
If any one has this problem this guide fix it for me: https://support.plesk.com/hc/en-us/articles/115001811053-Unable-to-connect-to-a-Plesk-server-via-FTP-when-FTP-ports-are-filtered-by-a-firewall-Connection-timed-out
