### ISSUE TITLE
No such file[2]

### ISSUE THREAD

**Issue by Hoto-Cocoa** [karikera/ftp-kr#70]
When i trying to upload file(edit, create...) task not applied and shows up this error.
This error shows up when right-click upload action and file watch upload action.

My workspace environment:
 * OS: Fedora 27
 * Architect: x86_64
 * VS Code Version: Version 1.20.1(Commit f88bbf9137d24d36d968ea6b2911786bfe103002)
 * ftp-kr Version: 1.3.16

Stack trace:
```Task: upload /asdf
platform: linux
arch: x64

[Error]
message: No such file[2]
code: 2

[Stack Trace]
Error: No such file
    at SFTPStream._transform (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/ssh2-streams/lib/sftp.js:410:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SFTPStream.Writable.write (_stream_writable.js:241:11)
    at Channel.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Channel.Readable.push (_stream_readable.js:136:10)
    at SSH2Stream.<anonymous> (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Object.promiseErrorWrap (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/util/util.ts:247:16)
    at SftpConnection.upload (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/vsutil/fileinterface.ts:91:10)
    at _blockTestWrap.client (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/ftpmgr.ts:341:51)
    at FtpManager.<anonymous> (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/ftpmgr.ts:142:48)
    at Generator.next (<anonymous>)
    at /home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpmgr.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpmgr.js:3:12)
    at util_1.promiseErrorWrap.connect.then (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/ftpmgr.ts:136:66)
    at <anonymous>
    at Object.promiseErrorWrap (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/util/util.ts:247:16)
    at FtpManager._blockTestWrap (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/ftpmgr.ts:136:10)
    at FtpManager.upload (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/ftpmgr.ts:341:15)
    at FtpCacher.<anonymous> (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/ftpcacher.ts:290:25)
    at Generator.next (<anonymous>)
    at /home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpcacher.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpcacher.js:3:12)
    at next (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/ftpcacher.ts:255:49)
    at FtpCacher.<anonymous> (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/src/ftpcacher.ts:315:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/leesj1221/.vscode/extensions/ruakr.ftp-kr-1.3.16/out/ftpcacher.js:4:58)
    at <anonymous>```

**Comment by karikera** [comment]
It looks like did not have permission to write to remote path.  
I will update error message to understand easily

**Comment by Hoto-Cocoa** [comment]
I re-checked this issue, this caused by my ftp-kr.json path configuration. thanks!
