### ISSUE TITLE
message: ftp-kr is busy: [First Connect] is being proceesed. Cannot run [First Connect]

### ISSUE THREAD

**Issue by peanutDD** [karikera/ftp-kr#89]
[Stack Trace]
Error: ftp-kr is busy: [First Connect] is being proceesed. Cannot run [First Connect]
	at Timeout.timeout.setTimeout [as _onTimeout] ([ftp-kr]/out/vsutil/work.js:62:35)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)

**Comment by xdedeone** [comment]
Try change connection protocol or port.

**Comment by Bluedimensional** [comment]
this happened to me when first trying to connect - turns out i had forgot to set the port number.
