### ISSUE TITLE
Doesn't seem to work with VSCode 1.23.1

### ISSUE THREAD

**Issue by vic-t** [karikera/ftp-kr#93]
I'm running a fresh install of VSCode 1.23.1 (x64) on Windows 10 and also downloaded and configured ftp-kr. 

I'm trying to connect to my ftp server through port 21. I can confirm that my settings work, tested using the command line ftp command in Windows. 

> ftp ftp.myserver.com

ftp-kr, on the other hand, can't finish the initialization. It's stuck in a loop, confirming it's connected but unable to list files in the directory. 

```
Trying to connect to ftp://ftp.myserver.com:21/www with user ftp123
Connected
list www
Trying to connect to ftp://ftp.myserver.com:21/www with user ftp123
Connected
list www
[This repeats over and over]
```

I tried reinstalling the extension, I tried changing the remotePath setting to nothing, to /, to the actual data path with and without leading /, nothing seems to help. 

I assume this is a bug.

**Comment by Rann1** [comment]
For me it connects normally. And I can browse the folders, but when opening a file I get the error below. Tried with multiple projects I usually work with daily. Keep getting the 'server not found error' in each different project. Tried reinstalling to no avail sadly.

`Error: Server not found: ftp://xxxx.xx@xxxx////xxxxx.xx/app/Mage.php
	at FtpTree.getServerFromUri (C:\Users\xxxxx\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:110:15)
	at FtpContentProvider.<anonymous> (C:\Users\xxxxx\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:38:48)
	at Generator.next (<anonymous>)
	at C:\Users\xxxxx\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\xxxxx\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:3:12)
	at FtpContentProvider.provideTextDocumentContent (C:\Users\xxxxx\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftptree.js:35:16)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:546:257
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:621
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:378)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:584)
	at e.$provideTextDocumentContent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:546:221)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:737)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:455)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:529)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:298)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:226
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:324
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)`

**Comment by flashxyz** [comment]
> I'm running a fresh install of VSCode 1.23.1 (x64) on Windows 10 and also downloaded and configured ftp-kr.
> 
> I'm trying to connect to my ftp server through port 21. I can confirm that my settings work, tested using the command line ftp command in Windows.
> 
> > ftp ftp.myserver.com
> 
> ftp-kr, on the other hand, can't finish the initialization. It's stuck in a loop, confirming it's connected but unable to list files in the directory.
> 
> ```
> Trying to connect to ftp://ftp.myserver.com:21/www with user ftp123
> Connected
> list www
> Trying to connect to ftp://ftp.myserver.com:21/www with user ftp123
> Connected
> list www
> [This repeats over and over]
> ```
> 
> I tried reinstalling the extension, I tried changing the remotePath setting to nothing, to /, to the actual data path with and without leading /, nothing seems to help.
> 
> I assume this is a bug.

same here with 1.29.1

**Comment by dabidi** [comment]
after update to version 1.31.1 (on windows) i have the same issue
```
Trying to connect to sftp://dev.mysite.pl//var/www/mysite.pl with user root
Connected
download /var/www/mysite.pl/checkout/partials/stepTwoSave.php
Trying to connect to sftp://dev.mysite.pl//var/www/mysite.pl with user dabidi
Connected
download /var/www/mysite.pl/checkout/partials/stepTwoSave.php
Trying to connect to sftp://dev.mysite.pl//var/www/mysite.pl with user dabidi
Connected
download /var/www/mysite.pl/checkout/partials/stepTwoSave.php
Trying to connect to sftp://dev.mysite.pl//var/www/mysite.pl with user dabidi
Connected
```

**Comment by Jorge1o1** [comment]
> after update to version 1.31.1 (on windows) i have the same issue
Same issue.

**Comment by dalanskis** [comment]
@dabidi I am experiencing the same issue. The extension just keeps trying to download my css.map over and over after I connect and try to upload.
