### ISSUE TITLE
list fail error. What does it happen?

### ISSUE THREAD

**Issue by mindgitrwx** [karikera/ftp-kr#96]
**Unexpected packet before version**
**list fail**

Ip connection to remote server has been successful, but no files or folders were listed. This is my personal logs. 

ftp-kr.json: loaded
Trying to connect to sftp://<!--personal ip:22>/. with user root
Connected
list .
list fail: .
Error: Unexpected packet before version
    at SFTPStream._transform (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\node_modules\ssh2-streams\lib\sftp.js:304:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\node_modules\ssh2-streams\lib\sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SFTPStream.Writable.write (_stream_writable.js:241:11)
    at Channel.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Channel.Readable.push (_stream_readable.js:136:10)
    at SSH2Stream.<anonymous> (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\node_modules\ssh2\lib\Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\node_modules\ssh2-streams\lib\ssh.js:3444:10)
    at SSH2Stream._transform (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\node_modules\ssh2-streams\lib\ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\node_modules\ssh2-streams\lib\ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SSH2Stream.Writable.write (_stream_writable.js:241:11)
    at Socket.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
    at Object.promiseErrorWrap (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\src\util\util.ts:247:16)
    at SftpConnection.list (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\src\vsutil\fileinterface.ts:164:10)
    at _blockTestWrap.client (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\src\ftpmgr.ts:356:51)
    at FtpManager.<anonymous> (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\src\ftpmgr.ts:142:48)
    at Generator.next (<anonymous>)
    at C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftpmgr.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftpmgr.js:3:12)
    at util_1.promiseErrorWrap.connect.then (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\src\ftpmgr.ts:136:66)
    at <anonymous>
    at Object.promiseErrorWrap (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\src\util\util.ts:247:16)
    at FtpManager._blockTestWrap (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\src\ftpmgr.ts:136:10)
    at FtpManager.list (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\src\ftpmgr.ts:356:15)
    at FtpCacher.<anonymous> (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\src\ftpcacher.ts:583:41)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\jonghyun\.vscode\extensions\ruakr.ftp-kr-1.3.16\out\ftpcacher.js:4:58)
    at <anonymous>

**Comment by mindgitrwx** [comment]
Self solution : It's fault of configuring of user name in ftp-kr.json. Amazon EC2 server name uses 'Ubuntu' , not 'root'. I changed it and this error has disappeared

**Comment by aniagarwal97** [comment]
How to provide .pem file for this connection?
